import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthKitProvider } from "@workos-inc/authkit-nextjs/components";
export const metadata: Metadata = {
  title: "Brev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthKitProvider>
        {" "}
        <body className="min-h-screen">
          <div className="background-gradient">
            <div className="gradient-orb orb-1"></div>
            <div className="gradient-orb orb-2"></div>
          </div>
          <main className="relative z-10">{children}</main>
        </body>
      </AuthKitProvider>
    </html>
  );
}
